function createfigure(X1, Y1, X2, Y2, Y3, Y4, Y5, Y6)
%CREATEFIGURE(X1, Y1, X2, Y2, Y3, Y4, Y5, Y6)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  Y5:  vector of y data
%  Y6:  vector of y data

%  Auto-generated by MATLAB on 12-Apr-2016 13:05:54

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,2,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'DisplayName','data','Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'Parent',subplot1,'DisplayName','fitted curve','Color',[1 0 0]);

% Create text
text('Parent',subplot1,'String','R^2 = 0,9804','Position',[100 1.8 0]);

% Create xlabel
xlabel('Vinkel [{\circ}]');

% Create ylabel
ylabel('Spænding [V]');

% Create title
title('Grøn - x-akse');

% Create subplot
subplot2 = subplot(3,2,3,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'on');

% Create plot
plot(X1,Y3,'Parent',subplot2,'DisplayName','data','Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y4,'Parent',subplot2,'DisplayName','fitted curve','Color',[1 0 0]);

% Create text
text('Parent',subplot2,'String','R^2 = 0,9800','Position',[100 1.8 0]);

% Create xlabel
xlabel('Vinkel [{\circ}]');

% Create ylabel
ylabel('Spænding [V]');

% Create title
title('Grøn - y-akse');

% Create subplot
subplot3 = subplot(3,2,5,'Parent',figure1);
box(subplot3,'on');
hold(subplot3,'on');

% Create plot
plot(X1,Y5,'Parent',subplot3,'DisplayName','data','Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y6,'Parent',subplot3,'DisplayName','fitted curve','Color',[1 0 0]);

% Create text
text('Parent',subplot3,'String','R^2 = 0,9812','Position',[100 1.8 0]);

% Create xlabel
xlabel('Vinkel [{\circ}]');

% Create ylabel
ylabel('Spænding [V]');

% Create title
title('Grøn - z-akse');

% Create subplot
subplot4 = subplot(3,2,2,'Parent',figure1);
box(subplot4,'on');
hold(subplot4,'on');

% Create plot
plot(X1,Y1,'Parent',subplot4,'DisplayName','data','Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'Parent',subplot4,'DisplayName','fitted curve','Color',[1 0 0]);

% Create text
text('Parent',subplot4,'String','R^2 = 0,9806','Position',[100 1.8 0]);

% Create xlabel
xlabel('Vinkel [{\circ}]');

% Create ylabel
ylabel('Spænding [V]');

% Create title
title('Rød - x-akse');

% Create subplot
subplot5 = subplot(3,2,4,'Parent',figure1);
box(subplot5,'on');
hold(subplot5,'on');

% Create plot
plot(X1,Y3,'Parent',subplot5,'DisplayName','data','Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y4,'Parent',subplot5,'DisplayName','fitted curve','Color',[1 0 0]);

% Create text
text('Parent',subplot5,'String','R^2 = 0,9790','Position',[100 1.8 0]);

% Create xlabel
xlabel('Vinkel [{\circ}]');

% Create ylabel
ylabel('Spænding [V]');

% Create title
title('Rød - y-akse');

% Create subplot
subplot6 = subplot(3,2,6,'Parent',figure1);
box(subplot6,'on');
hold(subplot6,'on');

% Create plot
plot(X1,Y5,'Parent',subplot6,'DisplayName','data','Marker','.',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y6,'Parent',subplot6,'DisplayName','fitted curve','Color',[1 0 0]);

% Create text
text('Parent',subplot6,'String','R^2 = 0,9791','Position',[100 1.8 0]);

% Create xlabel
xlabel('Vinkel [{\circ}]');

% Create ylabel
ylabel('Spænding [V]');

% Create title
title('Rød - z-akse');

