function [fitresult, gof] = createFits(grader, groenX, groenY, groenZ, roedX, roedY1, roedZ);
%CREATEFITS(GRADER,GROENX,GROENY,GROENZ,ROEDX,ROEDY1,ROEDZ)
%  Create fits.
%
%  Data for 'Grøn - x' fit:
%      X Input : grader
%      Y Output: groenX
%  Data for 'Grøn - y' fit:
%      X Input : grader
%      Y Output: groenY
%  Data for 'Grøn - z' fit:
%      X Input : grader
%      Y Output: groenZ
%  Data for 'Rød - x' fit:
%      X Input : grader
%      Y Output: roedX
%  Data for 'Rød - y' fit:
%      X Input : grader
%      Y Output: roedY1
%  Data for 'Rød - z' fit:
%      X Input : grader
%      Y Output: roedZ
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Apr-2016 10:57:13

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 6, 1 );
gof = struct( 'sse', cell( 6, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'Grøn - x'.
[xData1, yData1] = prepareCurveData( grader, groenX );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData1, yData1, ft );

%% Fit: 'Grøn - y'.
[xData2, yData2] = prepareCurveData( grader, groenY );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData2, yData2, ft );


%% Fit: 'Grøn - z'.
[xData3, yData3] = prepareCurveData( grader, groenZ );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData3, yData3, ft );

%% Fit: 'Rød - x'.
[xData4, yData4] = prepareCurveData( grader, flip(roedX) );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData4, yData4, ft );

%% Fit: 'Rød - y'.
[xData5, yData5] = prepareCurveData( grader, flip(roedY1) );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{5}, gof(5)] = fit( xData5, yData5, ft );

%% Fit: 'Rød - z'.
[xData6, yData6] = prepareCurveData( grader, roedZ );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{6}, gof(6)] = fit( xData6, yData6, ft );

%% Plot alle 
figure
subplot(3,2,1)
plot( fitresult{1}, xData1, yData1 );
text(100,1.8,'R^2 = 0,9804','FontSize',20)
xlabel('Vinkel [{\circ}]'); 
ylabel('Spænding [V]');
title('Grøn - x-akse');
set(gca,'fontsize',20);
grid off

subplot(3,2,3)
plot( fitresult{2}, xData2, yData2 );
text(100,1.8,'R^2 = 0,9800','FontSize',20)
xlabel('Vinkel [{\circ}]'); 
ylabel('Spænding [V]');
title('Grøn - y-akse');
set(gca,'fontsize',20);
grid off

subplot(3,2,5)
plot( fitresult{3}, xData3, yData3 );
text(100,1.8,'R^2 = 0,9812','FontSize',20)
xlabel('Vinkel [{\circ}]'); 
ylabel('Spænding [V]');
title('Grøn - z-akse');
set(gca,'fontsize',20);
grid off

subplot(3,2,2)
plot( fitresult{4}, xData4, yData4 );
text(100,1.8,'R^2 = 0,9806','FontSize',20)
xlabel('Vinkel [{\circ}]'); 
ylabel('Spænding [V]');
title('Rød - x-akse');
set(gca,'fontsize',20);
grid off

subplot(3,2,4)
plot( fitresult{5}, xData5, yData5 );
text(100,1.8,'R^2 = 0,9790','FontSize',20)
xlabel('Vinkel [{\circ}]'); 
ylabel('Spænding [V]');
title('Rød - y-akse');
set(gca,'fontsize',20);
grid off

subplot(3,2,6)
plot( fitresult{6}, xData6, yData6 );
text(100,1.8,'R^2 = 0,9791','FontSize',20)
xlabel('Vinkel [{\circ}]'); 
ylabel('Spænding [V]');
title('Rød - z-akse');
set(gca,'fontsize',20);
grid off


